### ISSUE TITLE
Rename `*.query` files to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [OffenesJena/OffeneGeodaten#1]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all `*.query` files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by ahzf** [comment]
I think it was only one file and this was changed now.

**Comment by FloEdelmann** [comment]
Thanks for the quick reaction! Unfortunately, I overlooked that the file is actually in Overpass XML format, not in Overpass QL. So it is not really affected by the new recommendation. Feel free to change it back or leave it is as now. Sorry for the inconvenience!
